<h1>Introduction to Numpy</h1>

In the following lessons you will learn:

<ul>
<li>How to import NumPy</li>
<li>How to create multidimensional NumPy ndarrays using various methods</li>
<li>How to access and change elements in ndarrays</li>
<li>How to load and save ndarrays</li>
<li>How to use slicing to select or change subsets of an ndarray</li>
<li>Understand the difference between a view and a copy an of ndarray</li>
<li>How to use Boolean indexing and set operations to select or change subsets of an ndarray</li>
<li>How to sort ndarrays</li>
<li>How to perform element-wise operations on ndarrays</li>
<li>Understand how NumPy uses broadcasting to perform operations on ndarrays of different sizes. </li>
</ul>

In [1]:
# Why use Numpy?
import numpy as np
import time as time

In [2]:
x = np.random.random(100000000)

In [3]:
# case1 - using plain python

start_time = time.time()
average = sum(x) / len(x)

print(f"Plain python - it took {time.time() - start_time} seconds to calculate the average: {average}")

"""
Plain python - it took `28.07101273536682` seconds to calculate the average: 0.4999669348542901
"""

Plain python - it took 38.88900136947632 seconds to calculate the average: 0.5000127661998851


'\nPlain python - it took `28.07101273536682` seconds to calculate the average: 0.4999669348542901\n'

In [4]:
# case 2 - using Numpy
start_time = time.time()
average = np.mean(x)

print(f"using Numpy - it took {time.time() - start_time} seconds to calculate the average: {average}")

"""
using Numpy - it took [0.24601483345031738] seconds to calculate the average: 0.4999669348542858
"""

using Numpy - it took 0.34699344635009766 seconds to calculate the average: 0.5000127661998417


'\nusing Numpy - it took [0.24601483345031738] seconds to calculate the average: 0.4999669348542858\n'

## Creating and Saving NumPy ndarrays

There are several ways to create ndarrays in NumPy. In the following lessons we will see two ways to create ndarrays:
<ol>
<li> Using regular Python lists
<li> Using built-in NumPy functions

In [5]:
# we import NumPy into Python
import numpy as np

# we create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])   # np.array(list)

# print the ndarray
print(f"x = {x}")

x = [1 2 3 4 5]


## Rank of an Array (numpy.ndarray.ndim)

Syntax:

`ndarray.ndim`  - x.ndim

In [6]:
# we get the Rank of an array (1 - D , 2 - D , N - D arrays)

# 1-D array (contains list - 1 refers to square brackets number)
x = np.array([1, 2, 3])
x.ndim

1

In [7]:
# 2-D array (contains list of lists - 2 refers to square brackets number)
Y = np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]]
    )
Y.ndim

2

In [8]:
# Here the`zeros()` is an inbuilt function that you'll study on the next page.
# The tuple (2, 3, 4( passed as an argument represents the shape of the ndarray

y = np.zeros((2,3,4))
y.ndim

3

## (Shape of an array) numpy.ndarray.shape
عدد الصفوف وعدد الأعمدة

Syntax:

`ndarray.shape`     - x.shape

<b>It returns a tuple representing the array dimensions </b>

## Type of array elements
نوع العناصر اللى جوة المصفوفة

(Elements of an array are of type {int32})

Syntax:

`ndarray.dtype`     - x.dtype

<b>The type tells us the data-type of the elements.  </b>

### Example 1.a - Using a 1-D Array of Integers


In [9]:
# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# We print information about x
print(f" x = {x}")
print(f" x has dimensions: {x.shape}")              # (5,)
print(f" x is an object of type: {type(x)}")        # `ndarray`
print(f" the elements of x are of type {x.dtype}")  # int64 - x are stored in memory as signed 64-bit integers

 x = [1 2 3 4 5]
 x has dimensions: (5,)
 x is an object of type: <class 'numpy.ndarray'>
 the elements of x are of type int32


### Example 1.b - Using 1-D Array of Strings


In [10]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

# هنطبع حبة معلومات عن المصفوفة، زى عدد الصفوف والأعمدة(الشيب)، ونوع العناصر بداخل المصفوفة(الدى تايب )، ونوع المصفوفة (التايب)
print(f" x = {x}")
print(f" x has dimensions: {x.shape} ")             # (2,)
print(f" x is an object of a type: {type(x)}")
print(f" the elements of x are a type: {x.dtype}")  # U5 - Unicode strings of 5 characters.

 x = ['Hello' 'World']
 x has dimensions: (2,) 
 x is an object of a type: <class 'numpy.ndarray'>
 the elements of x are a type: <U5


### Example 1.c - Using a 1-D Array of Mixed Datatype


In [11]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# هنطبع حبة معلومات عن المصفوفة، زى عدد الصفوف والأعمدة(الشيب)، ونوع العناصر بداخل المصفوفة(الدى تايب )، ونوع المصفوفة (التايب)
print(f" x = {x}")
print(f" x has dimensions: {x.shape} ")             # (3,)
print(f" x is an object of a type: {type(x)}")
print(f" the elements of x are a type: {x.dtype}")  # U11 - Unicode strings of 11 characters.

 x = ['1' '2' 'World']
 x has dimensions: (3,) 
 x is an object of a type: <class 'numpy.ndarray'>
 the elements of x are a type: <U11


## Using a 1-D Array to Demonstrate Upcasting in Numeric datatype


### Example 1.d - Using a 1-D Array of Int and Float


In [12]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)    # int64
print('The elements in x are of type:', y.dtype)    # float64
print('The elements in x are of type:', z.dtype)    # float64

The elements in x are of type: int32
The elements in x are of type: float64
The elements in x are of type: float64


### Example 1.e - Using a 1-D Array of Float, and specifying the datatype of each element as int64 

(Casting a 1-D Array of Float to an array of integers)

In [13]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print the dtype x
print('x = ', x)
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]
The elements in x are of type: int64


## (Size of an array - عدد عناصر المصفوفة) x.size
numpy.ndarray.size & Creating a 2-D array


### Example 2 - Using a 2-D Array (Rank #2 Array)



In [14]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([ 
    [1,2,3], 
    [4,5,6],
    [7,8,9], 
    [10,11,12]
    ])

# We print information about Y
print(f" Y (a rank 2 array): \n {Y} ")
print(f" Y has dimensions of: {Y.shape}")
print(f" Y has a total of {Y.size} elements ")
print(f" Y is an object of type: {type(Y)}")
print(f" The elements in Y are of type: {Y.dtype}")


 Y (a rank 2 array): 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 
 Y has dimensions of: (4, 3)
 Y has a total of 12 elements 
 Y is an object of type: <class 'numpy.ndarray'>
 The elements in Y are of type: int32


## Save the NumPy array to a File


### Example 3 - Save the NumPy array to a File


In [15]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as "saved_array"
np.save("saved_array",x)

### Example 3.1 - Load the NumPy array from our current directory


In [16]:
# We load the saved array from our current directory into variable y
y = np.load("saved_array.npy")

# we print y
print(f" y:\t{y}\n")

# we define a function to avoid geting `index error`, when calling a tuple parameters
def shape_rows_cols():
    shape_list = []
    for index in range(y.ndim + 1):
        try:
            shape_list.append(y.shape[index])
        except IndexError:
            shape_list.append(0)
    return shape_list


# We print information about the ndarray we loaded
print(f" y shape is: {y.shape} has {shape_rows_cols()[0]} rows and {shape_rows_cols()[1]} columns")
print(f" y has total of {y.size} elements")
print(f" y is an object of type: {type(y)}")
print(f" the type of y elements is: {y.dtype}")




 y:	[1 2 3 4 5]

 y shape is: (5,) has 5 rows and 0 columns
 y has total of 5 elements
 y is an object of type: <class 'numpy.ndarray'>
 the type of y elements is: int32


## Quiz: Creating and Saving NumPy ndarrays


In [17]:
import numpy as np

# create numpy array of letters a-j
letter_array =np.array(['a','b','c','d','e','f','g','h','i','j'])

print(f"Letters Array is: {letter_array}")

# get dtype of array
print(f" The elements of Letters Array are of {letter_array.dtype} type")


# get shape of array

# we define a function to avoid geting `index error`, when calling a tuple parameters
def shape_rows_cols():
    shape_list = []
    for index in range(letter_array.ndim + 1):
        try:
            shape_list.append(letter_array.shape[index])
        except IndexError:
            shape_list.append(0)
    return shape_list


print(f" letters array shape is: {letter_array.shape} has {shape_rows_cols()[0]} rows and {shape_rows_cols()[1]} columns")


# get size of array
print(f" letters_array has total of {letter_array.size} elements")


Letters Array is: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
 The elements of Letters Array are of <U1 type
 letters array shape is: (10,) has 10 rows and 0 columns
 letters_array has total of 10 elements


# Using Built-in Functions to Create ndarrays (Quiz 2)


### Example 1. Create a Numpy array of zeros with a desired shape


In [18]:
# We create a 3 x 4 ndarray full of zeros. 
X = np.zeros((3,4))

# We print X
print(f"X= \n{X}\n")

# We print information about X (shape - size - type - dtype - ndim{number of axis(rows,columns)} - )
print(f"X shape: {X.shape}")
print(f"X Size: {X.size}")
print(f"X type: {type(X)}")
print(f"X elements type: {X.dtype}")
print(f"X ndim: {X.ndim}")

X= 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

X shape: (3, 4)
X Size: 12
X type: <class 'numpy.ndarray'>
X elements type: float64
X ndim: 2


### Example 2. Create a Numpy array of ones


In [19]:
# We create a 3 x 2 ndarray full of ones. 
X = np.ones((3,2))

# We print X
print(f"X= \n{X}\n")

# We print information about X (shape - size - type - dtype - ndim{number of axis(rows,columns)} )
print(f" X has dimensions: {X.shape}")
print(f" X Size: {X.size}")
print(f" X is an object of type: {type(X)}")
print(f" The elements in X are of type: {X.dtype}")
print(f" The number of X axis: {X.ndim}")

X= 
[[1. 1.]
 [1. 1.]
 [1. 1.]]

 X has dimensions: (3, 2)
 X Size: 6
 X is an object of type: <class 'numpy.ndarray'>
 The elements in X are of type: float64
 The number of X axis: 2


### Example 3. Create a Numpy array of constants


In [20]:
# We create a 3 x 2 ndarray full of ones. 
X = np.full((2,3),5)

# We print X
print(f"X= \n{X}\n")

# We print information about X (shape - size - type - dtype - ndim{number of axis(rows,columns)} )
print(f" X has dimensions: {X.shape}")
print(f" X Size: {X.size}")
print(f" X is an object of type: {type(X)}")
print(f" The elements in X are of type: {X.dtype}")
print(f" The number of X axis: {X.ndim}")

X= 
[[5 5 5]
 [5 5 5]]

 X has dimensions: (2, 3)
 X Size: 6
 X is an object of type: <class 'numpy.ndarray'>
 The elements in X are of type: int32
 The number of X axis: 2


### Example 4 a. Create a Numpy array of an (eye)dentity matrix

مصفوفة القطر بتاعها ب 1 والباقى 0


In [21]:
# We create a 3 x 2 ndarray full of ones. 
X = np.eye((5))

# We print X
print(f"X= \n{X}\n")

# We print information about X (shape - size - type - dtype - ndim{number of axis(rows,columns)} )
print(f" X has dimensions: {X.shape}")
print(f" X Size: {X.size}")
print(f" X is an object of type: {type(X)}")
print(f" The elements in X are of type: {X.dtype}")
print(f" The number of X axis: {X.ndim}")

X= 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

 X has dimensions: (5, 5)
 X Size: 25
 X is an object of type: <class 'numpy.ndarray'>
 The elements in X are of type: float64
 The number of X axis: 2


### Example 4 b. Create a Numpy array of constants


In [22]:
# We create a 3 x 2 ndarray full of ones. 
X = np.diag([10,20,30,50])

# We print X
print(f"X= \n{X}\n")

# We print information about X (shape - size - type - dtype - ndim{number of axis(rows,columns)} )
print(f" X has dimensions: {X.shape}")
print(f" X Size: {X.size}")
print(f" X is an object of type: {type(X)}")
print(f" The elements in X are of type: {X.dtype}")
print(f" The number of X axis: {X.ndim}")

X= 
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]

 X has dimensions: (4, 4)
 X Size: 16
 X is an object of type: <class 'numpy.ndarray'>
 The elements in X are of type: int32
 The number of X axis: 2


## numpy.arange

Syntax:

`numpy.arange([start, ]stop, [step, ]dtype=None)`

### Example 5. Create a Numpy array of evenly spaced values in a given range, using 
`arange(stop_val)`

In [23]:
X = np.arange(0,10,2)

# We print X
print(f"X= \n{X}\n")

# We print information about X (shape - size - type - dtype - ndim{number of axis(rows,columns)} )
print(f" X has dimensions: {X.shape}")
print(f" X Size: {X.size}")
print(f" X is an object of type: {type(X)}")
print(f" The elements in X are of type: {X.dtype}")
print(f" The number of X axis: {X.ndim}")

X= 
[0 2 4 6 8]

 X has dimensions: (5,)
 X Size: 5
 X is an object of type: <class 'numpy.ndarray'>
 The elements in X are of type: int32
 The number of X axis: 1


### Example 6. Create a Numpy array using 
`arange(start_val, stop_val)`

In [24]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9. 
x = np.arange(4,10)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [4 5 6 7 8 9]

x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


### Example 7. Create a Numpy array using 
`arange(start_val, stop_val, step_size)`

In [25]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,14,3)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [ 1  4  7 10 13]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


## numpy.linspace
Syntax:

`numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)`

### Example 8. Create a Numpy array using 
`linspace(start, stop, n)` , with stop inclusive.

In [27]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
x = np.linspace(0,25,10, )    #num = num of integers(10)

# We print the ndarray
print()
print('x = \n', x)
print()

# We print information about the ndarray
print(f"{x.shape} - {x.size} - {type(x)} - {x.dtype} - {x.ndim} ")


x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

(10,) - 10 - <class 'numpy.ndarray'> - float64 - 1 


### Example 9. Create a Numpy array using 
`linspace(start, stop, n)`, with stop excluded.

In [28]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded.
x = np.linspace(0,25,10, endpoint=False)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


### Example 10. Create a Numpy array by feeding the output of `arange()` function to the  `reshape()` function.
Here, `arange()` function will give you a 1-D array, whereas the `reshape()` function will convert that 1-D array into a  desired shape. **Remember, that the  `size` of the final output must be as same as the `size` of the initial  1-D array.

In [29]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)

# We print x
print()
print('Original x = ', x)
print()

# We reshape x into a 4 x 5 ndarray 
x = np.reshape(x,(4,5))

# We print the reshaped x
print()
print('Reshaped x = \n', x)
print()

# We print information about the reshaped x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


### Example 11. Create a Numpy array by calling the `reshape()` function from the output of `arange()` function.
Notice the change in the arguments of `reshape()`

In [31]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4,5)

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


### Example 12. Create a rank 2 Numpy array by using the `reshape()` function.

In [32]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10,endpoint=False).reshape(5,2)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


### Example 13. Create a Numpy array using the `numpy.random.random()` function. 

In [35]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random((3,3))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.33667656 0.07302773 0.69967768]
 [0.1396164  0.4357127  0.42964831]
 [0.28983896 0.20643928 0.08686292]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


### Example 14. Create a Numpy array  using the `numpy.random.randint()` function. 

In [36]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).

X = np.random.randint(4,15,size=(3,2))  #randint(1st interval, 2nd open interval, (tuple of dimensions))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[10  9]
 [ 6  5]
 [14  7]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


### Example 15. Create a Numpy array of "Normal" distributed random numbers, using the `numpy.random.normal()` function. 

In [38]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(loc=0,scale=0.1,size=(1000,1000)) # loc:mean - scale: st.dev - size:(tuple of dimensions)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print(f"X has {(X > 0).sum()} positive numbers")


X = 
 [[-0.05161539 -0.1098724   0.00780874 ... -0.0366571  -0.07892038
  -0.09289829]
 [-0.01806215  0.04601715 -0.01720454 ... -0.13511219 -0.05163215
  -0.10172677]
 [-0.20891438  0.07293792 -0.23255732 ...  0.03537024  0.01110465
   0.05285507]
 ...
 [-0.11759123 -0.20973654 -0.05987486 ... -0.01639962  0.04196009
   0.23406572]
 [-0.20042179 -0.16248714 -0.1116584  ...  0.09643719 -0.01018633
   0.08183666]
 [-0.07246749 -0.04280439 -0.13189006 ... -0.08292032 -0.13492282
   0.07144316]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 3.5663115046110165e-05
The maximum value in X is: 0.4872152900881126
The minimum value in X is: -0.4668190098921501
X has 499778 negative numbers
X has 500222 positive numbers


## Accessing, Deleting, and Inserting Elements Into ndarrays


### Example 1. Access individual elements of 1-D array


In [40]:
import numpy as np

# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.arange(1,6,dtype=int)


# We print x
print()
print('x = ', x)
print()

# Let's access some elements with positive indices
print('This is First Element in x:', x[0]) 
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()


# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])


x =  [1 2 3 4 5]

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


### Example 2. Modify an element of 1-D array

In [42]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.linspace(1,5,num=5)

# We print the original x
print()
print('Original:\n x = ', x)
print()

# We change the fourth element in x from 4 to 20
x[3] = 20

# We print x after it was modified 
print('Modified:\n x = ', x)


Original:
 x =  [1. 2. 3. 4. 5.]

Modified:
 x =  [ 1.  2.  3. 20.  5.]


### Example 3. Access individual elements of 2-D array


In [44]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.linspace(1,9,num=9,dtype=int).reshape(3,3)

# We print X
print()
print('X = \n', X)
print()

# Let's access some elements in X 
print(f"This is (0,0) Element in X:{X[0,0]}")
print(f"This is (0,1) Element in X:{X[0,1]}")
print(f"This is (2,2) Element in X:{X[2,2]}")


X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

This is (0,0) Element in X:1
This is (0,1) Element in X:2
This is (2,2) Element in X:9


### Example 4. Modify an element of 2-D array             


In [49]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.linspace(1,9,num=9,dtype=int).reshape(3,3)

# We print the original x
print()
print('Original:\n X = \n', X)
print()

# We change the (0,0) element in X from a random choice from 1 to 20
X[0,0] = np.random.choice(21)

# We print X after it was modified 
print('Modified:\n X = \n', X)


Original:
 X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified:
 X = 
 [[16  2  3]
 [ 4  5  6]
 [ 7  8  9]]


### Example 5. Delete elements 


In [54]:
# We create a rank 1 ndarray 
x = np.linspace(1,5,5,dtype=int)

# We create a rank 2 ndarray
Y = np.linspace(1,9,num=9,dtype=int).reshape(3,3)

# We print x
print()
print('Original x = ', x)

# We delete the first and last element of x
x = np.delete(x,[0,-1])


# We print x with the first and last element deleted
print()
print('Modified x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We delete the first row of y
w = np.delete(Y,0,axis=0)        # axis 0 = rows reference

# We delete the first and last column of y
v = np.delete(Y, [0,-1], axis=1) # axis 1 = cols reference

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)


Original x =  [1 2 3 4 5]

Modified x =  [2 3 4]

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]

v = 
 [[2]
 [5]
 [8]]


### Example 6. Append elements


In [55]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])

# We print x
print()
print('Original x = ', x)

# We append the integer 6 to x
x = np.append(x, 6)

# We print x
print()
print('x = ', x)

# We append the integer 7 and 8 to x
x = np.append(x, [7,8])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

# We print v
print()
print('v = \n', v)

# We print q
print()
print('q = \n', q)


Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]

Original Y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


### Example 7.  Insert elements


In [57]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])

# We print x with the inserted elements
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)

# We insert a column full of 5s between the first and second column of y

v = np.insert(Y,1,5, axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)



Original x =  [1 2 5 6 7]

x =  [1 2 3 4 5 6 7]

Original Y = 
 [[1 2 3]
 [7 8 9]]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[1 5 2 3]
 [7 5 8 9]]


## Slicing
1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]


### Example 1. Slicing in a 2-D ndarray 


In [58]:
import numpy as np

# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)

# We can select the same elements as above using method 2
W = X[1:,2:5]

# We print W
print()
print('W = \n', W)

# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

# We print Y
print()
print('Y = \n', Y)

# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)

# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print()
print('q = ', q)

# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print()
print('R = \n', R)



X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

v =  [10 11 12 13 14]

q =  [ 2  7 12 17]

R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


### Example 2. Slicing and editing elements in a 2-D ndarray 

### Example 3. Demonstrate the `copy()` function

### Example 4. Use an array as indices to either make slices, select, or change elements

### Example 5. Demonstrate the `diag()` function

### Example 6. Demonstrate the `unique()` function